// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzpiDo8ITlrrfujGaTB1ruxZNSzzWQ7I',
    appId: '1:897537632000:web:50173c839628992bf235e5',
    messagingSenderId: '897537632000',
    projectId: 'smartbudgt-61a71',
    authDomain: 'smartbudgt-61a71.firebaseapp.com',
    storageBucket: 'smartbudgt-61a71.firebasestorage.app',
    measurementId: 'G-QPZ11T5F7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFwvlN_kZVzSUdqwCHcT8fpD6yguV_ig',
    appId: '1:897537632000:android:44bb0ec64ff5f8f8f235e5',
    messagingSenderId: '897537632000',
    projectId: 'smartbudgt-61a71',
    storageBucket: 'smartbudgt-61a71.firebasestorage.app',
  );
}
